.\" $Id: $
.\" CHECKIN $Date: $
.TH pcbitctrl 8 "" "ISDN 4 Linux 2.99" "Linux System Administration"
.PD 0

.SH NAME
pcbitctrl \- PCBIT-D ISDN card firmware loader

.SH SYNOPSIS
.B pcbitctrl
{-p | -s} [-f firmware-file] [-b board-number] [-f]

.SH DESCRIPTION
Sorry, no complete description as yet. I'm working on it.
In the meantime, read /usr/doc/isdnutils/pcbit if you understand Portugese...
Apparently the PCBIT-D card is only used in Portugal?

.SH AUTHOR
.B pcbitctrl
was written by Pedro Roque Marques <roque@di.fc.ul.pt>.

This manual page was written by Paul Slootman <paul@debian.org>,
for Debian GNU/Linux and isdn4linux.
