.\" $Id: $
.\" CHECKIN $Date: $
.TH isdnconf 8 "" "ISDN 4 Linux 2.99" "Linux System Administration"
.PD 0

.SH NAME
isdnconf \- manipulate ISDNlog configuration files

.SH SYNOPSIS
.B isdnconf
{ -A | -D | -M areacode number }
[-dwslimqgV1] [-a alias] [-n number] [-t number?] [-f callerfile]
[-c areacode] [-M areacode number]

.SH DESCRIPTION
Sorry, no proper description as yet. I'm working on it.

.SH FILES

.SH AUTHOR
.B isdnconf
was written by Stefan Luethje <luethje@sl-gw.lake.de>.

This manual page is being written by Paul Slootman <paul@debian.org>,
for Debian GNU/Linux and isdn4linux.
