.\" $Id: imontty.8,v 1.1 1998/02/10 17:29:06 paul Exp $
.\" CHECKIN $Date: 1998/02/10 17:29:06 $
.TH imontty 8 "" "ISDN 4 Linux 2.99" "Linux System Administration"
.PD 0

.SH NAME
imontty \- print out ISDN line status

.SH SYNOPSIS
.B imontty
[phonebook]

.SH DESCRIPTION
.B imontty
is a handy program to print out the status of all ISDN lines
managed by the isdn4linux system.

No options are supported. You may supply a filename containing a simple
phonebook, which is then used to replace phone numbers with names.
The output should look like this:

.nf
ISDN channel status:

Channel                 Usage Type  Number
-----------------------------------------------------------------
line0                   Out   Net   07900734
line0                   Off

.fi
.B Usage
is one of Off(line), Out(going), In(coming) or Excl(usive).

.B Type
is one of raw (raw device), Modem (modem/tty emulation), Net
(IP interface), Voice (voice call) or Fax (fax transmission).

.B Number
is either the called party's number (outgoing) or the
calling party number (incoming).

The format of the phonebook file is

.nf
0123456789	Name
0234567890	Another Name
.fi

i.e. phone number and name, separated by one tab. The name may contain
spaces etc.

.SH FILES
.TP
.B /dev/isdninfo
To get the status from the kernel.

.SH AUTHOR
.B imontty
was written by Volker Goetz <volker@oops.franken.de>.

This manual page was written by Paul Slootman <paul@debian.org>,
for Debian GNU/Linux and isdn4linux.
