.TH pcbitctl 1L "ISDN" "Linux" \" -*- nroff -*-
.SH NAME
pcbitctl \- PCBIT-D firmware loader
.SH SYNOPSIS
.B pcbitctl
[\-ps] [\-l firmware] [\-b devnum]
[\-\-ping] [\-\-stop]
[\-\-force] [\-\-board devnum]
.SH DESCRIPTION
This manual page documents the
.B PCBIT-D
firmware loader and device driver control program.
.SS OPTIONS
.TP
.I "\-s, \-\-stop"
Signals the device driver to stop all comunication with the
.B PCBIT-D
board. This is usefull if you want to reload the firmware.
.TP
.I "\-p, \-\-ping"
Issue a
.B PING_188
message. This option can be used to test if the
.B 80188
processor is running and if the device firmware was correctly loaded.
.TP 
.I "\-l file, \--load file"
Load the firmware
.I file
into the device Ram Dual Port (RDP). Comunication between the device and the 
driver must be stoped.
.TP
.I "\-f, \-\-force"
If a 
.I load
is to be performed and the driver is not stoped,
this option causes
.B pcbitctl
to issue a driver reset and to stop the driver.
.TP
.I "\-b devnum, \-\-board devnum"
Selects the board (default 0), since the driver can control up to 4 devices.
.SH BUGS
The 
.B stpd.1
and
.B stpd.2
files must be present in the current directory for the load operation.
.SH SEE ALSO
isdnctrl(8), Linux Kernel Documentation.
.SH AUTHOR
Pedro Roque (roque@di.fc.ul.pt)
.SH COPYRIGHT
Copyright (C) 1996 Universidade de Lisboa.
