#! /bin/sh
# postinst script for capiutils

set -e

case "$1" in
    configure)
	rm -f /etc/hotplug/blacklist.d/capiutils 2>/dev/null
	rmdir /etc/hotplug/blacklist.d 2>/dev/null || true

        cd /dev
        echo "Note: running MAKEDEV to create CAPI devices in /dev..."
        MAKEDEV capi
	;;

    abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    	;;
esac

#DEBHELPER#

exit 0
