.\" $Id: $
.\" CHECKIN $Date: $
.TH isdnconfig 8 "1998/12/02" "ISDN 4 Linux 3.0beta1" "Linux System Administration"
.PD 0

.SH NAME
isdnconfig \- configure the Debian isdnutils package

.SH SYNOPSIS
.B isdnconfig

.SH DESCRIPTION
.B isdnconfig
is used to interactively enable any required ISDN daemons and other programs;
skeleton configuration files are installed. Those configuration files need to
be edited by hand before anything useful will happen. Upon starting the
isdnutils programs, the init.d script will tell you if any files are not yet
configured manually.

.SH AUTHOR
.B isdnconfig
was written by Andreas Jellinghaus specifically for Debian GNU/Linux and
isdn4linux, and is now maintained by Paul Slootman <paul@debian.org>, 
