#!/bin/sh

# Example netdown script for xmonisdn
# Do with it what you want.

# This removes the outgoing phone number(s), so that dial-on-demand is
# disabled; then the line is hung up.
# As this is only an example, there is 'exit 0' at the beginning of the
# script. Remove it after changing this script to your liking.

exit 0

[ -f /etc/isdn/device.ippp0 ] || exit 0
eval `grep '^	isdnctrl addphone' /etc/isdn/device.ippp0 | sed 's,addphone,delphone,'`
/sbin/isdnctrl hangup ippp0
