#!/bin/sh

# Example netup script for xmonisdn
# Do with it what you want.

# This adds the outgoing phone number(s), so that dial-on-demand can be
# used.
# As this is only an example, there is 'exit 0' at the beginning of the
# script. Remove it after changing this script to your liking.

exit 0

[ -f /etc/isdn/device.ippp0 ] || exit 0
eval `grep '^	isdnctrl addphone' /etc/isdn/device.ippp0`
