#!/bin/sh

if [ -d /etc/isdnlog ];
then
	(cd /etc/isdnlog/; for A in `ls`; do mv $A ../isdn/old.$A ;
	done)
	rm -rf /etc/isdnlog
fi

for A in vboxgetty isdnlog isdn ; do
	if [ -f /etc/init.d/$A ]; then
		/etc/init.d/$A stop;
		mv /etc/init.d/$A /etc/isdn/old.init.d.$A
		update-rc.d $A remove >/dev/null 
	fi
done

