#!/bin/bash

set -e

if dpkg --compare-versions `dpkg -l libc6 | tail -1 | awk '{ print $3 }'` lt 2.1.2
then
    echo "Your libc6 version is too old for this version of isdnutils;"
    echo "this shouldn't happen (unless your tried to install isdnutils manually)."
    echo "Please use dselect or apt to upgrade your system."
    echo "The installation of isdnutils is now being aborted."
    exit 1
fi

OLDPACKAGES='isdnlog ipppd xisdnutils'
PACKAGES=''

for i in $OLDPACKAGES 
do 
	dpkg -s $i \
		| awk '/^Status/ { print $3 } ' \
		| fgrep -v "ok" > /dev/null \
		&& PACKAGES="$PACKAGES $i"; 
done

# any old package installed ?
if [ ! -z "$PACKAGES" ]
then # yes ...
	echo " I see that you have one or more of the old isdn packages installed:

$PACKAGES

These packages are integrated into isdnutils. You need to remove them
before you can proceed to install isdnutils.

This is how to do it:
	From the commandline call:            
	dpkg --remove --force-depends $PACKAGES

Press ENTER to continue 	[Return]"
	read
	exit 1                   
fi

# check for old netup / netdown files

[ "x$1" != xupgrade ] && exit 0

if [ -u /usr/X11R6/bin/xmonisdn ]; then
	chmod u-s /usr/X11R6/bin/xmonisdn
	echo "xmonisdn is no longer setuid root, as that is a potential security hole."
	echo "Read the xmonisdn manpage for more information."
	echo ''
	if [ -x /usr/sbin/suidunregister ]; then
		suidunregister -s isdnutils /usr/X11R6/bin/xmonisdn
	fi
fi

if dpkg --compare-versions "$2" "<<" "1:3.0"
then
	[ -f /etc/isdn/netup -o -f /etc/isdn/netdown ] || exit 0
	echo "
You have /etc/isdn/netup and/or /etc/isdn/netdown.
The functionality of those are replaced by:

	- /etc/isdn/xisdnload-net{up,down}
	- /etc/isdn/xmonisdn-net{up,down}

This has been done so that the different behaviours of xisdnload and xmonisdn
can be catered for. See the abovementioned files for more info.
The old netup / netdown scripts have been renamed to netup.old and netdown.old.
Please remove them manually.

Press ENTER to continue 	[Return]"
	read
	[ -f /etc/isdn/netup   ] && mv -f /etc/isdn/netup   /etc/isdn/netup.old
	[ -f /etc/isdn/netdown ] && mv -f /etc/isdn/netdown /etc/isdn/netdown.old
fi

# check for RADIUS installation
RADIUSCONF=/etc/radiusclient/radiusclient.conf
if dpkg --compare-versions "$2" ">=" "1:3.0-10" &&
   dpkg --compare-versions "$2" "<=" "1:3.0-11"
then
	if [ -s $RADIUSCONF -a ! -x /usr/sbin/ipppd.radius ]
	then
		cat <<EOF
I see you have $RADIUSCONF and an ipppd that
supports RADIUS.
The ipppd in this version of isdnutils does NOT support RADIUS due to
problems when not using RADIUS and using dynamic IP addresses; RADIUS
support in ipppd will be made available as a separate package in the
future.

For now, choose one of the following options:

  1 or y) simply overwrite ipppd
  2 or r) rename the current ipppd to ipppd.radius so that you can still use it
  3 or n or q) abort the installation

  1 is default.

EOF
		while :; do
			echo -n 'Choice: '
			read ans bla
			case x"$ans" in
				x1|xy|x)	ans=y;;
				x2|xr)		ans=r;;
				x3|xn|xq)	echo "Aborting."; exit 1;;
				*)		echo "Enter 1 or 2 or 3 !";;
			esac
			if [ "$ans" = y ]; then
				break
			fi
			if [ "$ans" = r ]; then
				mv -f /usr/sbin/ipppd /usr/sbin/ipppd.radius
				break
			fi
		done
	fi
fi

if dpkg --compare-versions "$2" "<<" "1:3.0-14" && \
	[ -s /etc/ppp/ip-up.d/isdnutils -o -s /etc/ppp/ip-down.d/isdnutils ]
then
	cat <<'EOF'

There is a mechanism for running scripts when a PPP link goes up and when it
goes down. When a link goes up the scripts in /etc/ppp/ip-up.d/ are run in
order, and when it goes down the scripts in /etc/ppp/ip-down.d/ are run, also
in order. The problem (up to now) was that the isdnutils script should be run
as the first script, but by its naming it was not. Starting from this version,
the "up" script should be called "00-isdnutils", and the "down" script should
be called "99-isdnutils". However, you currently have the old names.

If you have no idea what I'm talking about, choose number 1.

1 - I can delete the current scripts.
    If you have not made any changes, this is the best option.

2 - I can resolve this by renaming the existing scripts to the new names.
    This is the second-best option.

3 - I can also leave the scripts alone.
    You must then check and modify the setup manually.

EOF
	ans=NOK
	while :; do
		echo -n 'Choice: '
		read ans bla
		case x"$ans" in
			x1)	ans=OK
				echo 'I will delete the current scripts.'
				# OK, not really deleting...
				mv -f /etc/ppp/ip-up.d/isdnutils /etc/ppp/ip-up.d/isdnutils.dpkg-old
				mv -f /etc/ppp/ip-down.d/isdnutils /etc/ppp/ip-down.d/isdnutils.dpkg-old
				;;
			x2)	ans=OK
				echo 'I will rename the current scripts.'
				rm -f /etc/ppp/ip-up.d/00-isdnutils
				mv -f /etc/ppp/ip-up.d/isdnutils /etc/ppp/ip-up.d/00-isdnutils
				rm -f /etc/ppp/ip-down.d/99-isdnutils
				mv -f /etc/ppp/ip-down.d/isdnutils /etc/ppp/ip-down.d/99-isdnutils
				;;
			x3)	ans=OK
				echo 'I will leave the scripts alone.'
				echo 'You must check the scripts by hand!'
				;;
			*)	echo "Enter 1 or 2 or 3 !";;
		esac
		[ "$ans" = OK ] && break
	done
fi

exit 0
