.\" $Id: isdntime.man,v 1.1 1997/09/04 11:34:17 aj Exp $
.\" CHECKIN $Date: 1997/09/04 11:34:17 $
.TH isdntime 5 "@MANDATE@" "ISDN 4 Linux @I4LVERSION@" "Linux System Administration"
.SH NAME
isdntime \- time format in isdn configuration files (isdnlog and vbox)
.SH Description
This man page describes the time format used in all isdn configuration
files (isdnlog and vbox).

All time values have to be in 24 hour format (0-23). Every time value is
recalculated into a start and end time, even if only one number is
given.

If no minute is given, 0 is considered for start time, 59 for end time.

The special entry "*" is used for always (00:00:00-23:59:59), the special
character "!" is used for never.  Start and end times are always
inclusive.

.SH EXAMPLES

20:15-21:14 is used as 20:15:00-21:14:59.

20 is used as 20:00:00-20:59:59.

08-11 is used as 08:00:00-11:59:59.

12-15:30 is used as 12:00:00-15:30:59.

.SH DAY OF WEEK

Day of week settings are given as abbreviations, separated with comma.

You may use the English abbreviations (MON,TUE,WED,THU,FRI,SAT,SUN) or
the German ones (MO,DI,MI,DO,FR,SA,SO).

.SH AUTHOR
This manual page was written by Andreas Jellinghaus <aj@debian.org>,
for Debian GNU/Linux and isdn4linux.
