.TH IMONTTY 8 "25. August 1995"
.UC 4
.SH NAME
imontty \- report status of ISDN devices
.SH SYNOPSIS
.B imontty
[-i dev] [-f [-d sec]]
.br
.SH DESCRIPTION
.B imontty
reports the Status of the ISDN lines of isdn4linux. Each ISDN
channel is described by one line. "Dr/Ch" shows the actual
Driver and hardware channel of this particular driver which is
attached to the "Channel X" indicated at the beginning of the
line. Direction is incoming, outgoing or free. Usage is one of
"raw", "tty emulation", "IP interface", "voice" or "fax".
.LP
.SH OPTIONS
.TP 8
.B -i dev
Change the ISDN info device. Default is /dev/isdninfo
.TP 8
.B -f
Print the status of the ISDN lines continously, similar to
.B top\c
(1). To stop the output type Ctrl-C.
.TP 8
.B -d sec
Set the delay seconds between to screen refreshes. Default is 5
seconds.
.LP
.SH BUGS
The code to clear the screen is "hardcoded" and fits only for
ANSI/vt100 screens. No termcap/terminfo entries are used.
.LP
.SH FILES
/dev/isdninfo	The info device of the ISDN driver
.SH SEE ALSO
.I isdninfo\c
(4),
.I isdnctrl\c
(8),
.I icnctrl\c
(8),
.I telesctrl\c
(8).
.LP
.SH AUTHOR
Volker Goetz <volker@oops.franken.de>
