#! /bin/sh
##
## $Id: mkdev,v 1.1 1997/04/28 16:55:00 michael Exp $

./utils/mksed <./doc/de/vbox.sgml.in >/home/www/local/tools/vbox/vbox.sgml

cd /home/www/local/tools/vbox

sgml2html -img -l vbox.sgml
sgml2txt -l vbox.sgml
