#!/bin/sh

case "$1" in
	0931xxxxxxx)
	splay -q /sounds/fido
	;;
	07131xxxxxx)
	splay -q /sounds/poph
	;;
	0931xxxxxxx)
	splay -q /sounds/imnet
	;;
	0911xxxxxxx)
	splay -q /sounds/hub-n
	;;
	0931xxxxxxx)
	splay -q /sounds/dls
	;;
	*)
	splay -q /sounds/dial
	;;
esac

